/*
Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed n, 
find the sum of the even-valued terms.

fiboEvenSum(34) should return 44.
fiboEvenSum(60) should return 44.
fiboEvenSum(1000) should return 798.
fiboEvenSum(100000) should return 60696.
fiboEvenSum(4000000) should return 4613732.
*/

function fiboEvenSum(n) {
    let temp = 0
    let temp1 = 1
    let nth = 0
    let evens = 0
    while (nth <= n){
      nth = temp + temp1
      temp = temp1
      temp1 = nth
   
      if((nth%2)==0){
        console.log("ok")
        evens += nth
      }
    }
  
    return evens;
  }